version: '3.1'
services:
   nginx:
      image: nginx
      container_name: nginx
      ports:
         - 80:80
         - 8080:8080
         - 443:443
      volumes:
         - ./nginx/metrics.conf:/etc/nginx/conf.d/metrics.conf
      command: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"
      restart: unless-stopped

   cadvisor:
      image: gcr.io/cadvisor/cadvisor
      container_name: cadvisor
      ports:
         - 8888:8888
      restart: unless-stopped
      volumes:
         - /:/rootfs:ro
         - /var/run:/var/run:rw
         - /sys:/sys:ro
         - /var/lib/docker/:/var/lib/docker:ro
      depends_on:
         - nginx

   nginx-prometheus-exporter:
      image: nginx/nginx-prometheus-exporter
      container_name: nginx-prometheus-exporter
      ports:
         - 9113:9113
      restart: unless-stopped
      command:
         - '--nginx.scrape-uri=http://nginx:8080/status'
      depends_on:
         - cadvisor

   prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
         - 9090:9090
      restart: unless-stopped
      volumes:
         - ./prometheus:/etc/prometheus
         - prom_data:/prometheus
      command:
         - '--config.file=/etc/prometheus/prometheus.yaml'
      depends_on:
         - cadvisor

   grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
         - 3000:3000
      restart: unless-stopped
      environment:
         - GF_SECURITY_ADMIN_USER=admin
         - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
         - ./grafana:/etc/grafana/provisioning/datasources
         - grafana_data:/var/lib/grafana
      depends_on:
         - prometheus

volumes:
   prom_data:
   grafana_data:
